FROM python:3.12-slim

#  Ваш код здесь #
COPY . .
RUN DEBIAN_FRONTEND=noninteractive && apt update && apt install -y uvicorn 
RUN python3 -m venv venv
RUN DEBIAN_FRONTEND=noninteractive && . venv/bin/activate && pip install -r requirements.txt

# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"] 
